const TEXTS = {
  GE: {
    signin: "შესვლა",
    signup: "რეგისტრაცია",
    landigTitle: "სადაც საუკეთესო ნიჭი ხვდება ტოპ კომპანიებს",
    landigSerchTalant: "მიიღეთ შესაძლებლობა, რომელიც აძლიერებს თქვენს",
    landigSerchTalantTitle: "დაქირავება მინდა",
    landigSerchJob: "იპოვეთ თქვენთვის სასურველი ფრილანსერი",
    landigSerchJobTitle: "მე ვარ ფრილანსერი",
    aboutus: "ჩვენს შესახებ",
    contact: "კონტაქტი",
    open: "გადასვლა",
    getStarted: "ახლა ნახვა",
    name: "სახელი",
    surname: "გვარი",
    email: "მეილი",
    password: "პაროლი",
    createAccount: "Შექმენით ანგარიში",
    doHaveAcc: "არ გაქვთ ანგარიში?",
  },

  EN: {
    signin: "sign in",
    signup: "sign up",
    landigTitle: "Where Top Talent Meets Top Companies",
    landigSerchTalant: "Get the opportunity that boost your",
    landigSerchTalantTitle: "I Want to Hire",
    landigSerchJob: "Find your desirable Freelancer",
    landigSerchJobTitle: "I’m a Freelancer",
    aboutus: "About us",
    contact: "Contact",
    open: "open",
    getStarted: "Get Started",
    name: "name",
    surname: "surname",
    email: "E-mail",
    password: "Password",
    createAccount: "Create an Account",
    doHaveAcc: "Don’t Have An Account?",
  },
};

export default TEXTS;
